export const SET_URLS = "SET_URLS";
export const ADD_URL = "ADD_URL";
export const DELETE_URL = "DELETE_URL";
export const DELETE_URLS = "DELETE_URLS";
// export const UPDATE_ACTIVE_GROUP_TITLE = "UPDATE_ACTIVE_GROUP_TITLE";
// export const UPDATE_ACTIVE_GROUP_PUBLIC = "UPDATE_ACTIVE_GROUP_PUBLIC";
