export const SET_GROUPS = "SET_GROUPS";
export const ADD_GROUP = "ADD_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";
export const SET_ACTIVE_GROUP = "SET_ACTIVE_GROUP";
export const UPDATE_ACTIVE_GROUP_TITLE = "UPDATE_ACTIVE_GROUP_TITLE";
export const UPDATE_ACTIVE_GROUP_PUBLIC = "UPDATE_ACTIVE_GROUP_PUBLIC";
